name: Deploy Infrastructure 


on:
  push:
    branches: [ master ]
    paths:
    
     - '.github/workflows/main.yml'
    # - 'src/biceps/*'
   
permissions:
      id-token: write
      contents: read
      
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    env:
      companybbr: "cm"
      Applicationname: "website"
      ResourceGroupLocation: "eastus"
      type: "internal"
      Appplicationtype: "portal"
      envtype: "dev"
      appID: "test-shree"
      sku: "F1"
      linuxFxVersion : "node|14-lts"
      

    steps:
    
      # Checkout code
      - uses: actions/checkout@main
      
       # Log into Azure
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          # Specify the script here.
          inlineScript: 
             #!/bin/bash
             az group create --name rg-${{ env.companybbr }}-${{ env.envtype }}-${{ env.Applicationname }}-${{env.appID}} --location ${{ env.ResourceGroupLocation }} --tags "type=${{ env.type }}" "ApplicationType=${{ env.Appplicationtype }}"

      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          # Specify the script here
          inlineScript: 
             #!/bin/bash
               az group create --name rg-${{ env.companybbr }}-${{ env.envtype }}-security-${{env.appID}} --location ${{ env.ResourceGroupLocation }} --tags "type=${{ env.type }}" "ApplicationType=${{ env.Appplicationtype }}"


            
            
       # this step to configuire App Service...
          
          
          
       # Deploy Bicep file
      - name: Deploy App Service Plan
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rg-${{ env.companybbr }}-${{ env.envtype }}-${{ env.Applicationname }}-${{env.appID}}
          template: src/biceps/app_plan_svc.bicep
          parameters: "appPlanName=${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} sku=${{env.sku}} webAppName=${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} linuxFxVersion=${{env.linuxFxVersion}} "
          failOnStdErr: false
      



       # Deploy vnet spoke.............
      - name: Deploy Spoke vNet infrastructure 
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rg-${{ env.companybbr }}-${{ env.envtype }}-security-${{env.appID}}
          template: src/biceps/vnet_spoke.bicep
          parameters: "name=vnet-${{ env.companybbr }}-${{ env.envtype }}"
          failOnStdErr: false
          
      # Deploy vnet hub............
      - name: Deploy Hub vNet infrastructure 
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rg-${{ env.companybbr }}-${{ env.envtype }}-security-${{env.appID}}
          template: src/biceps/vnet_hub.bicep
          parameters: "name=vnet-${{ env.companybbr }}-${{ env.envtype }}"
          failOnStdErr: false



          
        # Vnet-Integration
      
      - name: Azure CLI Action to Vnet-Integration
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az webapp vnet-integration add -g rg-${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} -n wapp-${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} --vnet vnet-${{ env.companybbr }}-${{ env.envtype }}-spoke --subnet /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-${{ env.companybbr }}-${{ env.envtype }}-security-${{env.appID}}/providers/Microsoft.Network/virtualNetworks/vnet-${{ env.companybbr }}-${{ env.envtype }}-spoke/subnets/appsrv-subnet


        # Add Access Restriction
          
      - name: Azure CLI Action to Restrict Access
        uses: Azure/cli@v1
        with:
          # Specify the script here
          inlineScript: |
             az webapp config access-restriction add --resource-group rg-${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} --name wapp-${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} --action Deny --ip-address 0.0.0.0/32 --priority 100 --vnet-resource-group rg-${{ env.companybbr }}-${{ env.envtype }}-security-${{env.appID}}
             az webapp config access-restriction add --resource-group rg-${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} --name wapp-${{ env.companybbr }}-${{ env.envtype }}-website-${{env.appID}} --action Allow --vnet-name vnet-${{ env.companybbr }}-${{ env.envtype }}-hub --subnet gateway-subnet --priority 99 rg-${{ env.companybbr }}-${{ env.envtype }}-security-${{env.appID}}
         
      

          
             

        

          
      
